In [1]:
import cv2

In [2]:
## Method Definition
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
## Scale ands crop your faces
def face_extractor(img):
    ## first argument : img
    ## second argument : scalefactor(how much image size will be reduced at each image scale)
    ## third argument : how many neighors each rectangle should have
    faces = face_classifier.detectMultiScale(img, 1.3, 5)
    if faces == ():
        return None
    
    ## Crop all the faces found
    for(x,y,w,h) in faces:
        x = x-10;
        y = y-10;
        
        cropped_face = img[y:y+h+50, x:x+w+50]
    
    return cropped_face

In [4]:
## Initialize webcam
cap = cv2.VideoCapture(0)
count = 0

## Collect 100 samples of my face from the webcam input
while True:
    _, frame = cap.read()
    ## Method calling
    if face_extractor(frame) is not None:
        count += 1
        face = cv2.resize(face_extractor(frame), (400, 400))
        
        ## Save file in the specified directory
        file_name_path = './Images for visualization/sudhir.' + str(count) + '.jpg'
        cv2.imwrite(file_name_path, face)
        
        
        ## put count on images and display me the live count
        cv2.putText(face, str(count), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
        cv2.imshow('Face Cropper', face)
    else:
        print("Face not found")
        pass
    
    if cv2.waitKey(1) == 13 or count == 100:
        break

        
cap.release()
cv2.destroyAllWindows()

print("Dataset Creation task is successfully done")

C:\Users\sudhi\AppData\Local\Temp\ipykernel_780\2054343106.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if faces == ():


Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not f

Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Dataset Creation task is successfully do

# code for file transfar from one folder to another

In [7]:
import numpy as np
def my_label(image_name):
    name = image_name.split('.')[-3] 
    # if you have two person in your dataset
#     if name=="Ishwar":
#         return np.array([1,0])
#     elif name=="Manish":
#         return np.array([0,1])
    
    
    # if you have three person in your dataset
    if name=="sudhir":
        return np.array([1,0,0])
    elif name=="srishu":
        return np.array([0,1,0])
    elif name=="sanatan":
        return np.array([0,0,1])

In [8]:
import os
from random import shuffle
from tqdm import tqdm
def my_data():
    data = []
    for img in tqdm(os.listdir("Images for visualization")):
        path=os.path.join("Images for visualization",img)
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        data.append([np.array(img_data), my_label(img)])
    shuffle(data)  
    return data

In [9]:
data = my_data()

100%|███████████████████████████████████████████████████████████████████████████████| 300/300 [00:01<00:00, 289.42it/s]


In [10]:
data


[[array([[147, 135, 124, ..., 195, 196, 195],
         [167, 123, 144, ..., 196, 195, 195],
         [157, 113, 120, ..., 195, 194, 198],
         ...,
         [ 66,  42,  90, ..., 105, 139, 172],
         [ 34,  31,  52, ...,  53,  55,  58],
         [ 30,  28,  29, ...,  50,  51,  51]], dtype=uint8),
  array([0, 0, 1])],
 [array([[158, 158, 159, ..., 165, 165, 165],
         [158, 159, 160, ..., 165, 165, 165],
         [161, 159, 161, ..., 165, 164, 165],
         ...,
         [ 19,  18,  24, ..., 185, 186, 186],
         [ 15,  20,  23, ..., 184, 184, 185],
         [ 14,  19,  23, ..., 181, 183, 183]], dtype=uint8),
  array([0, 1, 0])],
 [array([[168, 169, 170, ..., 173, 173, 173],
         [169, 169, 169, ..., 175, 174, 173],
         [169, 169, 167, ..., 174, 174, 175],
         ...,
         [ 19,  25,  26, ..., 195, 195, 194],
         [ 21,  25,  28, ..., 194, 193, 193],
         [ 22,  25,  30, ..., 192, 191, 193]], dtype=uint8),
  array([0, 1, 0])],
 [array([[251, 251, 25

In [67]:
train = data[:240]  
test = data[240:]
X_train = np.array([i[0] for i in train]).reshape(-1,50,50,1)
print(X_train.shape)
y_train = [i[1] for i in train]
X_test = np.array([i[0] for i in test]).reshape(-1,50,50,1)
print(X_test.shape)
y_test = [i[1] for i in test]

(240, 50, 50, 1)
(60, 50, 50, 1)


In [68]:
# import warnings
# warnings.filterwarnings('ignore')

import tensorflow as tf
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

Instructions for updating:
non-resource variables are not supported in the long term
curses is not supported on this machine (please install/reinstall curses for an optimal experience)


In [69]:
tf.reset_default_graph()
convnet = input_data(shape=[50,50,1])
convnet = conv_2d(convnet, 32, 5, activation='relu')
# 32 filters and stride=5 so that the filter will move 5 pixel or unit at a time
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 128, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)
convnet = fully_connected(convnet, 3, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate = 0.001, loss='categorical_crossentropy')
model = tflearn.DNN(convnet, tensorboard_verbose=1)
model.fit(X_train, y_train, n_epoch=12, validation_set=(X_test, y_test), show_metric = True, run_id="FRS" )

AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'